version: '2'
services:
    tmc-app:
        image: tmc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://tmc-postgresql:5432/TMC
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tmc-postgresql:
        extends:
            file: postgresql.yml
            service: tmc-postgresql
